# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: netcon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "netcon.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cnetcon.proto\x12\x06netcon"\xe6\x01\n\x07request\x12\x16\n\tmessageId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bmessageType\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12+\n\x0brequestType\x18\x03 \x01(\x0e\x32\x11.netcon.request_eH\x02\x88\x01\x01\x12\x17\n\nrequestMsg\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nrequestVal\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_messageIdB\x0e\n\x0c_messageTypeB\x0e\n\x0c_requestTypeB\r\n\x0b_requestMsgB\r\n\x0b_requestVal"\xee\x01\n\x08response\x12\x16\n\tmessageId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bmessageType\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12-\n\x0cresponseType\x18\x03 \x01(\x0e\x32\x12.netcon.response_eH\x02\x88\x01\x01\x12\x18\n\x0bresponseMsg\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0bresponseVal\x18\x05 \x01(\tH\x04\x88\x01\x01\x42\x0c\n\n_messageIdB\x0e\n\x0c_messageTypeB\x0f\n\r_responseTypeB\x0e\n\x0c_responseMsgB\x0e\n\x0c_responseVal":\n\x08\x65nvelope\x12\x11\n\tencrypted\x18\x01 \x01(\x08\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c*u\n\trequest_e\x12"\n\x1eSERVERDATA_REQUEST_EXECCOMMAND\x10\x00\x12\x1b\n\x17SERVERDATA_REQUEST_AUTH\x10\x01\x12\'\n#SERVERDATA_REQUEST_SEND_CONSOLE_LOG\x10\x02*O\n\nresponse_e\x12\x1c\n\x18SERVERDATA_RESPONSE_AUTH\x10\x00\x12#\n\x1fSERVERDATA_RESPONSE_CONSOLE_LOG\x10\x01\x42\x02H\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "netcon_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"H\003"
    _globals["_REQUEST_E"]._serialized_start = 558
    _globals["_REQUEST_E"]._serialized_end = 675
    _globals["_RESPONSE_E"]._serialized_start = 677
    _globals["_RESPONSE_E"]._serialized_end = 756
    _globals["_REQUEST"]._serialized_start = 25
    _globals["_REQUEST"]._serialized_end = 255
    _globals["_RESPONSE"]._serialized_start = 258
    _globals["_RESPONSE"]._serialized_end = 496
    _globals["_ENVELOPE"]._serialized_start = 498
    _globals["_ENVELOPE"]._serialized_end = 556
# @@protoc_insertion_point(module_scope)
